language: csharp
mono: none
sudo: required
dist: xenial
addons:
    snaps:
        - name: dotnet-sdk
          classic: true
          channel: latest/stable
script:
    - sudo snap alias dotnet-sdk.dotnet dotnet
    - dotnet --version
    - dotnet restore
    - dotnet build /p:Configuration=Release NumericalAnalysis.sln
    - dotnet test UnitTest/UnitTest.csproj 
global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
